// -*- c++ -*-
// Generated by gmmproc 2.46.0 -- DO NOT MODIFY!
#ifndef _GIOMM_DBUSSUBTREEVTABLE_P_H
#define _GIOMM_DBUSSUBTREEVTABLE_P_H


#include <glibmm/private/object_p.h>


#endif /* _GIOMM_DBUSSUBTREEVTABLE_P_H */

